print("*** Vehicle Registration Center")
print(" ")
username = input("Enter username: ")
password = input("Enter password: ")

print("** Admin Menu**")
print("   ----------  ")
print(" ")
print("1:Add a registrar")
print("2:Change password of registrar")
print("3:View all registrars")
print("4:Log out")
print(" ")
adminOption = input("Enter your option: ")
